using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WebBrowserProject
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            // Create the form layout. If you are using Visual Studio,
            // you can replace this code with code generated by the designer.
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }
    }
}
